### ISSUE TITLE
Crash at the startup [0df4e9d] + Helping the project

### ISSUE THREAD

**Issue by UltraStars3000** [paulsapps/alive#66]
## Hello

Today, I've tried to compile the open-source, everything was alright, but when I launched Alive.exe, I got this error message :
![screenshot_20160722115607](https://cloud.githubusercontent.com/assets/14246308/17053660/52c83ba0-5003-11e6-82c5-5a8ca8cb0303.png)
When I "Abort" or "Ignore", the program close, and when I "Retry", it's stop to work.

> Assertion failed: IsArray(), file C:\Users\Benjamin\alive\3rdParty\rapidjson\include\rapidjson/document.h, line 1637

I searched in this file but I don't what's wrong with this line :

`Array GetArray() { RAPIDJSON_ASSERT(IsArray()); return Array(*this); }`

I'm not very good at coding, so I need your help to fix it please.

For information, I use the _**fs**_ branch

**Comment by MrSapps** [comment]
This is because that branch is heavily WIP - the resources.json file is out of date.  Although it would be better to wait until I push a new version of resources.json. I didn't want to bloat out  the repo by constantly pushing new versions of it since its around 3mb per generation.

For now you can use this one:

https://gist.github.com/paulsapps/9b51ee91b99eba34f64508cd9b68fc2e

Edit: For clarity the error is caused by trying to read an array in the json that doesn't exist in the older format. The code should probably be updated to handle this and simply say that the resources.json format is unknown or missing required fields.

**Comment by UltraStars3000** [comment]
Oh okay, I understand your choice.

But, I really want to help you, but I'm don't know too much in code, so I don't know how can I help you, maybe for translation in other languages or else.
I can learning a language like C++, but I don't know if this will be helpful.

**Comment by MrSapps** [comment]
There are many tasks that do not require coding that need to be done. If you drop by IRC I can explain :)

**Comment by UltraStars3000** [comment]
I'm ready, there is when I'm avaible on IRC:
Everyday (until the 1st September) : 11am-12am, 1pm-7pm, 8pm-9pm
(GMT+1)
